export interface FilmsEntity { 
  title: string,
  episode_id: number,
  opening_crawl: string,
  director: string,
  producer: string,
  release_data: string,
  characters: string[],
  planets: string[],
  startships: string[],
  species: string[],
  url: string,
  created: string,
  edited: string,
}